language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
sudo: false
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc

notifications:
  email:
    on_success: never
